version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: docker build
      - run: docker pull
workflows:
  version: 2
  building:
    jobs:
      - build
