version: 2
jobs:
  build:
    docker:
      - image: alpine/alpine:3.9
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
workflows:
  version: 2
  building:
    jobs:
      - build
