version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t dos2009/redmoon:8.0 .
      - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push dos2009/redmoon:latest  
workflows:
  version: 2
  building:
    jobs:
      - build
